
FROM maven:3.6.3-jdk-8-slim AS build
WORKDIR /home/app
COPY . /home/app
RUN mvn -f /home/app/pom.xml clean package -DskipTests

FROM openjdk:8-jdk-alpine
EXPOSE 8081
COPY --from=build /home/app/target/*.jar order-generator-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "sh", "-c", "java -jar /order-generator-0.0.1-SNAPSHOT.jar" ]